### ISSUE TITLE
AttributeError: 'DeepLDA_CV' object has no attribute 'loss_train'

### ISSUE THREAD

**Issue by thangckt** [luigibonati/mlcvs#25]
Dear Developers,

I try to run a tutorial provide in this link: https://mlcvs.readthedocs.io/en/latest/notebooks/ala2_deeplda.html
After training the model, I try to access the attribute `loss_train`
Then the code raises error:

```py
... \py39mlcvs\lib\site-packages\torch\nn\modules\module.py:1269, in Module.__getattr__(self, name)
   1267     if name in modules:
   1268         return modules[name]
-> 1269 raise AttributeError("'{}' object has no attribute '{}'".format(
   1270     type(self).__name__, name))

AttributeError: 'DeepLDA_CV' object has no attribute 'loss_train'
```

May be that attribute has not been implemented yet.

**Comment by luigibonati** [comment]
Hi Thang, 
which version are you using? If you are using the master branch can you try using one of the stable [releases](https://github.com/luigibonati/mlcvs/releases/tag/v0.2.1)? It might be that there are some breaking changes in the master branch that have not yet been updated in the tutorials.
You can also clone them e.g. by:
`git clone https://github.com/luigibonati/mlcvs.git -b v0.2.1`

**Comment by thangckt** [comment]
Dear @luigibonati 

I tried with `v0.2.1` and `master` branch, both yield the same error

**Comment by thangckt** [comment]
after looking at the source code, I realize that there is no attribute 'loss_train' in the implemented models.
Instead, there is `model.logs['loss_train']`

So the code in the tutorial should be change:

from 
```
loss_train = [x.cpu() for x in model.loss_train]
loss_valid = [x.cpu() for x in model.logs.loss_valid]
```
to
```
loss_train = [x.cpu() for x in model.logs['loss_train']]
loss_valid = [x.cpu() for x in model.logs['loss_valid']]
```

**Comment by luigibonati** [comment]
Thanks, I fixed the tutorials! Yes, we had moved to the logs without updating the tutorial in the master branch. 

Regarding the other error, you need to initialize the correct size of LDA / TICA eigenvectors, which determine the number of CVs (at the beginning they are equal to the number of nodes in the last layer). The easiest workaround is to train for one epoch before loading the checkpoint. This has already been fixed in the upcoming version by forcing one to choose the number of eigenvectors when instantiating a new object.
